[package]
name = "korrupt"
version = "0.1.0"
authors = ["PhirosWolf <phiroswolf@tuta.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
